// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tradeCaptureMessage.proto

package com.abnamro.challenge.futuretxn.messages;

public final class TradeCaptureProto {
  private TradeCaptureProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TradeCaptureMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TradeCaptureMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string key = 1;</code>
     * @return The key.
     */
    java.lang.String getKey();
    /**
     * <code>string key = 1;</code>
     * @return The bytes for key.
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>string meta = 2;</code>
     * @return The meta.
     */
    java.lang.String getMeta();
    /**
     * <code>string meta = 2;</code>
     * @return The bytes for meta.
     */
    com.google.protobuf.ByteString
        getMetaBytes();

    /**
     * <code>string rawMessage = 3;</code>
     * @return The rawMessage.
     */
    java.lang.String getRawMessage();
    /**
     * <code>string rawMessage = 3;</code>
     * @return The bytes for rawMessage.
     */
    com.google.protobuf.ByteString
        getRawMessageBytes();
  }
  /**
   * Protobuf type {@code TradeCaptureMessage}
   */
  public static final class TradeCaptureMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TradeCaptureMessage)
      TradeCaptureMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TradeCaptureMessage.newBuilder() to construct.
    private TradeCaptureMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TradeCaptureMessage() {
      key_ = "";
      meta_ = "";
      rawMessage_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TradeCaptureMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TradeCaptureMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              key_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              meta_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              rawMessage_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.internal_static_TradeCaptureMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.internal_static_TradeCaptureMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.TradeCaptureMessage.class, com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.TradeCaptureMessage.Builder.class);
    }

    public static final int KEY_FIELD_NUMBER = 1;
    private volatile java.lang.Object key_;
    /**
     * <code>string key = 1;</code>
     * @return The key.
     */
    @java.lang.Override
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <code>string key = 1;</code>
     * @return The bytes for key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int META_FIELD_NUMBER = 2;
    private volatile java.lang.Object meta_;
    /**
     * <code>string meta = 2;</code>
     * @return The meta.
     */
    @java.lang.Override
    public java.lang.String getMeta() {
      java.lang.Object ref = meta_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        meta_ = s;
        return s;
      }
    }
    /**
     * <code>string meta = 2;</code>
     * @return The bytes for meta.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMetaBytes() {
      java.lang.Object ref = meta_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        meta_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RAWMESSAGE_FIELD_NUMBER = 3;
    private volatile java.lang.Object rawMessage_;
    /**
     * <code>string rawMessage = 3;</code>
     * @return The rawMessage.
     */
    @java.lang.Override
    public java.lang.String getRawMessage() {
      java.lang.Object ref = rawMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rawMessage_ = s;
        return s;
      }
    }
    /**
     * <code>string rawMessage = 3;</code>
     * @return The bytes for rawMessage.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRawMessageBytes() {
      java.lang.Object ref = rawMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rawMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
      }
      if (!getMetaBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, meta_);
      }
      if (!getRawMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, rawMessage_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
      }
      if (!getMetaBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, meta_);
      }
      if (!getRawMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, rawMessage_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.TradeCaptureMessage)) {
        return super.equals(obj);
      }
      com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.TradeCaptureMessage other = (com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.TradeCaptureMessage) obj;

      if (!getKey()
          .equals(other.getKey())) return false;
      if (!getMeta()
          .equals(other.getMeta())) return false;
      if (!getRawMessage()
          .equals(other.getRawMessage())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      hash = (37 * hash) + META_FIELD_NUMBER;
      hash = (53 * hash) + getMeta().hashCode();
      hash = (37 * hash) + RAWMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getRawMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.TradeCaptureMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.TradeCaptureMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.TradeCaptureMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.TradeCaptureMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.TradeCaptureMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.TradeCaptureMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.TradeCaptureMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.TradeCaptureMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.TradeCaptureMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.TradeCaptureMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.TradeCaptureMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.TradeCaptureMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.TradeCaptureMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TradeCaptureMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TradeCaptureMessage)
        com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.TradeCaptureMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.internal_static_TradeCaptureMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.internal_static_TradeCaptureMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.TradeCaptureMessage.class, com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.TradeCaptureMessage.Builder.class);
      }

      // Construct using com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.TradeCaptureMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        key_ = "";

        meta_ = "";

        rawMessage_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.internal_static_TradeCaptureMessage_descriptor;
      }

      @java.lang.Override
      public com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.TradeCaptureMessage getDefaultInstanceForType() {
        return com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.TradeCaptureMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.TradeCaptureMessage build() {
        com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.TradeCaptureMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.TradeCaptureMessage buildPartial() {
        com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.TradeCaptureMessage result = new com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.TradeCaptureMessage(this);
        result.key_ = key_;
        result.meta_ = meta_;
        result.rawMessage_ = rawMessage_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.TradeCaptureMessage) {
          return mergeFrom((com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.TradeCaptureMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.TradeCaptureMessage other) {
        if (other == com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.TradeCaptureMessage.getDefaultInstance()) return this;
        if (!other.getKey().isEmpty()) {
          key_ = other.key_;
          onChanged();
        }
        if (!other.getMeta().isEmpty()) {
          meta_ = other.meta_;
          onChanged();
        }
        if (!other.getRawMessage().isEmpty()) {
          rawMessage_ = other.rawMessage_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.TradeCaptureMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.TradeCaptureMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <code>string key = 1;</code>
       * @return The key.
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       * @return The bytes for key.
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       * @param value The bytes for key to set.
       * @return This builder for chaining.
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        key_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object meta_ = "";
      /**
       * <code>string meta = 2;</code>
       * @return The meta.
       */
      public java.lang.String getMeta() {
        java.lang.Object ref = meta_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          meta_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string meta = 2;</code>
       * @return The bytes for meta.
       */
      public com.google.protobuf.ByteString
          getMetaBytes() {
        java.lang.Object ref = meta_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          meta_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string meta = 2;</code>
       * @param value The meta to set.
       * @return This builder for chaining.
       */
      public Builder setMeta(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        meta_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string meta = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMeta() {
        
        meta_ = getDefaultInstance().getMeta();
        onChanged();
        return this;
      }
      /**
       * <code>string meta = 2;</code>
       * @param value The bytes for meta to set.
       * @return This builder for chaining.
       */
      public Builder setMetaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        meta_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object rawMessage_ = "";
      /**
       * <code>string rawMessage = 3;</code>
       * @return The rawMessage.
       */
      public java.lang.String getRawMessage() {
        java.lang.Object ref = rawMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rawMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string rawMessage = 3;</code>
       * @return The bytes for rawMessage.
       */
      public com.google.protobuf.ByteString
          getRawMessageBytes() {
        java.lang.Object ref = rawMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rawMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string rawMessage = 3;</code>
       * @param value The rawMessage to set.
       * @return This builder for chaining.
       */
      public Builder setRawMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rawMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string rawMessage = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRawMessage() {
        
        rawMessage_ = getDefaultInstance().getRawMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string rawMessage = 3;</code>
       * @param value The bytes for rawMessage to set.
       * @return This builder for chaining.
       */
      public Builder setRawMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        rawMessage_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TradeCaptureMessage)
    }

    // @@protoc_insertion_point(class_scope:TradeCaptureMessage)
    private static final com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.TradeCaptureMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.TradeCaptureMessage();
    }

    public static com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.TradeCaptureMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TradeCaptureMessage>
        PARSER = new com.google.protobuf.AbstractParser<TradeCaptureMessage>() {
      @java.lang.Override
      public TradeCaptureMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TradeCaptureMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TradeCaptureMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TradeCaptureMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.abnamro.challenge.futuretxn.messages.TradeCaptureProto.TradeCaptureMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TradeCaptureMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TradeCaptureMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031tradeCaptureMessage.proto\"D\n\023TradeCapt" +
      "ureMessage\022\013\n\003key\030\001 \001(\t\022\014\n\004meta\030\002 \001(\t\022\022\n" +
      "\nrawMessage\030\003 \001(\tB=\n(com.abnamro.challen" +
      "ge.futuretxn.messagesB\021TradeCaptureProto" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_TradeCaptureMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TradeCaptureMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TradeCaptureMessage_descriptor,
        new java.lang.String[] { "Key", "Meta", "RawMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
